### ISSUE TITLE
rel="alternate" en PDF

### ISSUE THREAD

**Issue by aitormendez** [aitormendez/iac-web#46]
Luis, ¿puedes poner esto a la etiqueta `<a>`que genera el PDF de los documentos?

`rel="alternate"`

**Comment by muihlinn** [comment]
El primer enlace del texto "enlace a capón", lleva el `rel="alternate"`, no hay diferencia.
Resumiendo:
- Hay que modificar pdf.css para incluir estas deficiones o unas mejores, que cubran todos los casos en uso :
```css
@font-face{
	font-family: 'Asap';
	font-style: normal;
	font-weight: 400;
	src: url('http://iac/fonts/Asap/Asap-400.ttf')  format('truetype');
}
@font-face{
	font-family: 'Asap';
	font-style : bold;
	font-weight: 700;
	src: url('http://iac/fonts/Asap/Asap-700.ttf')  format('truetype');
}
```
- Hay que modificar los paths a los que hace referencia en el css para que los cargue efectivamente al estar ya integrado (IAC, ASAP...).

- Homenaje no parece reconocerla, o bien tiene problemas similares, algo parecido debe ocurrir con los otros estilos que presentan fallos (ariadna, los enlaces... ), y probablemente la solución pase por hacer algo similar a lo que se ha hecho con Asap.

[f492a90216b2efdf86649345b62746ce.pdf](https://github.com/aitormendez/iac-web/files/29957/f492a90216b2efdf86649345b62746ce.pdf)

**Nota** Esto es una anotación fundamentalmente para mí, porque estos cambios se van a sobreescribir la próxima vez que cargue tu repositorio en mi proyecto y necesitaré recordarlos cuando cerremos el asunto. No obstante, implementa lo que puedas en este repositorio

**Comment by aitormendez** [comment]
Hasta donde yo veo, así está en el CSS actual:

`@font-face {
  font-family: 'Asap';
  src: url(../fonts/Asap/Asap-700.eot);
  src: url(../fonts/Asap/Asap-700.eot?#iefix) format('embedded-opentype'), url(../fonts/Asap/Asap-700.woff) format('woff'), url(../fonts/Asap/Asap-700.ttf) format('truetype'), url(../fonts/Asap/Asap-700.svg#Asap) format('svg');
  font-weight: 700;
  font-style: normal;
}
@font-face {
  font-family: 'Asap';
  src: url(../fonts/Asap/Asap-400-Italic.eot);
  src: url(../fonts/Asap/Asap-400-Italic.eot?#iefix) format('embedded-opentype'), url(../fonts/Asap/Asap-400-Italic.woff) format('woff'), url(../fonts/Asap/Asap-400-Italic.ttf) format('truetype'), url(../fonts/Asap/Asap-400-Italic.svg#Asap) format('svg');
  font-weight: 400;
  font-style: italic;
}
@font-face {
  font-family: 'Asap';
  src: url(../fonts/Asap/Asap-700-Italic.eot);
  src: url(../fonts/Asap/Asap-700-Italic.eot?#iefix) format('embedded-opentype'), url(../fonts/Asap/Asap-700-Italic.woff) format('woff'), url(../fonts/Asap/Asap-700-Italic.ttf) format('truetype'), url(../fonts/Asap/Asap-700-Italic.svg#Asap) format('svg');
  font-weight: 700;
  font-style: italic;
}`

**Comment by muihlinn** [comment]
No es lo que aparece en pdf.css una vez compilado. O al menos no es lo que me aparece al recompilarlo. 

Si no están esas definiciones explicitamente en el css el parser no las encuentra.

**Comment by aitormendez** [comment]
Perdón, se me olvidó añadir la tarea de compilación de LESS para el PDF. Ya está, prueba a ver.
e13f3e6f906a3bf982302a980358cc15e1f6a079

**Comment by muihlinn** [comment]
ErrorException in Font_WOFF.php line 49:
gzuncompress(): data error

Voy a hacer unas modificaciones en el css compilado a ver.

**Comment by muihlinn** [comment]
solo los reconoce si los dejo así, además de cambiarles los paths, El mayor problema es que no hay definido un `style: bold` (que no sé si es correcto, creo que no) y si no está no lo incluye. Por lo demás  no veo diferencia con el pdf que te envié.

Sigue saliendo mal la cabecera y ariadna, imagino que por lo mismo.
Va a ser más rápido que te instales el dompdf y le pases el código de tu plantilla para que vayas afinando sobre la marcha.

```css
@font-face {
  font-family: 'Asap';
  font-style: normal;
  font-weight: 400;

  src: url(http://iac/fonts/Asap/Asap-400.ttf) format('truetype'), url(http://iac/fonts/Asap/Asap-400.svg#Asap) format('svg');
}
@font-face {
  font-family: 'Asap';
  font-style: bold;
  font-weight: 700;

  src: url(http://iac/fonts/Asap/Asap-700.ttf) format('truetype'), url(http://iac/fonts/Asap/Asap-700.svg#Asap) format('svg');
}
@font-face {
  font-family: 'Asap';
  font-style: italic;
  font-weight: 400;

  src: url(http://iac/fonts/Asap/Asap-400-Italic.ttf) format('truetype'), url(http://iac/fonts/Asap/Asap-400-Italic.svg#Asap) format('svg');
}
@font-face {
  font-family: 'Asap';
  font-style: bold italic;
  font-weight: 700;

  src: url(http://iac/fonts/Asap/Asap-700-Italic.ttf) format('truetype'), url(http://iac/fonts/Asap/Asap-700-Italic.svg#Asap) format('svg');
}
```
