### ISSUE TITLE
@font-face ASAP 700 en pdf.css

### ISSUE THREAD

**Issue by muihlinn** [aitormendez/iac-web#99]
`font-style` es normal cuando (creo) debería ser `bold`. No sé cómo debería ir `bold italic`

Supongo que aquí, en la 2ª línea [ less-iac/default-fonts.less ]:

```less
.EmbedAsap( "../fonts/Asap/Asap-400", 400, normal );
.EmbedAsap( "../fonts/Asap/Asap-700", 700, normal );
.EmbedAsap( "../fonts/Asap/Asap-400-Italic", 400, italic );
.EmbedAsap( "../fonts/Asap/Asap-700-Italic", 700, italic );
```
Que es la causa de algunos fallos que encontraba en las tipografías de los PDFs que no eran las que deberían ser. 

Es simplemente para que en posibles futuras correcciones en tu repositorio incorporen esta modificación para no romper la generación de pdfs

**Por clarificar:** se genera esto esto en pdf.css pero con `font-style: normal;` Funciona correctamente cuando lo cambio a `font-style:bold`

```css
@font-face {
  font-family: 'Asap';
  font-style: bold;
  font-weight: 700;

  src: url(../fonts/Asap/Asap-700.eot);
  src: url(../fonts/Asap/Asap-700.eot?#iefix) format('embedded-opentype'), url(../fonts/Asap/Asap-700.woff) format('woff'), url(../fonts/Asap/Asap-700.ttf) format('truetype'), url(../fonts/Asap/Asap-700.svg#Asap) format('svg');
}
```

**Comment by aitormendez** [comment]
Bien visto. Lo cambio.

**Comment by aitormendez** [comment]
No, no. Lo he mirado y está bien. Fíjate en la función:
```less
.EmbedAsap( @path, @weight: normal, @style: normal )
```
Primero va el path, luego el peso y luego el estilo. No se puede poner el peso donde va el estilo.

http://www.w3schools.com/CSS/css_font.asp

**Comment by muihlinn** [comment]
En un vistazo rápido a la especificación 2.1 es como tú dices, pero –entiendo por el ejemplo en el link de abajo– que Asap 400 y 700 se llaman exactamente igual, y quizás no deberían. No me hagas mucho caso que este asunto de las tipografías y sus familias es terra incógnita para mí.

https://www.w3.org/TR/CSS2/fonts.html#font-styling

**Comment by aitormendez** [comment]
Sí, deberían. Las dos son asap, una con peso 400 y otra con peso 700

**Comment by aitormendez** [comment]
Luis, creo que ya sé cuál es la solución. Prueba con esto:
```css
@font-face {
  font-family: 'Asap';
  font-style: normal;
  font-weight: bold;

  src: url(../fonts/Asap/Asap-700.eot);
  src: url(../fonts/Asap/Asap-700.eot?#iefix) format('embedded-opentype'), url(../fonts/Asap/Asap-700.woff) format('woff'), url(../fonts/Asap/Asap-700.ttf) format('truetype'), url(../fonts/Asap/Asap-700.svg#Asap) format('svg');
}
```
Si te funciona lo cambiamos en el código fuente
